#!/bin/bash
OUTPUT="grists"
GRIST=""
COST=""
ITEMSTACK=""
METADATA="false"
OFFSET=2
ITEM=$1
if [[ "$1" =~ ^[0-9]+$ ]] ; then
	ITEM="$2"
	ITEMSTACK=", 1, $1"
	OFFSET=3
	METADATA="true"
fi

for i in ${@:$OFFSET} ; do
	if [[ "$i" =~ ^[0-9]+$ ]] ; then
		COST="$COST""$i, "
	else
		GRIST="$GRIST""GristType.$i, "
	fi
done
#echo "$GRIST ${
echo "GristRegistry.addGristConversion(new ItemStack(Block.$ITEM$ITEMSTACK), $METADATA, new GristSet(new GristType[] {${GRIST%??}}, new int[] {${COST%??}}));">>$OUTPUT
