#!/bin/bash
OUTPUT="grists"
GRIST=""
COST=""
ITEMSTACK=""
METADATA="false"
OFFSET=3
CLASS=$1
ITEM=$2
if [[ "$2" =~ ^[0-9]+$ ]] ; then
	ITEM="$3"
	ITEMSTACK=", 1, $2"
	OFFSET=4
	METADATA="true"
fi

for i in ${@:$OFFSET} ; do
	if [[ "$i" =~ ^[0-9]+$ ]] ; then
		COST="$COST""$i, "
	else
		GRIST="$GRIST""GristType.$i, "
	fi
done
echo "GristRegistry.addGristConversion(new ItemStack($CLASS.$ITEM$ITEMSTACK), $METADATA, new GristSet(new GristType[] {${GRIST%??}}, new int[] {${COST%??}}));">>$OUTPUT
